server:
  port: 7001

eureka:
  instance:
    # 单机
    #hostname: localhost
    # 集群
    hostname: eureka7001.com
  client:
    # false 表示不向注册中心注册自己
    register-with-eureka: false
    # false 表示自己就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    fetch-registry: false
    service-url:
    # 设置与Eureka Server交互的地址查询服务和注册服务都需要依赖这个地址  单机
      #defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
      # 单机就是自己
      defaultZone: http://eureka7001.com:7001/eureka/
      # 集群
      #defaultZone: http://eureka7002.com:7002/eureka/
